- packages/styleguide-native/index.ts
- packages/styleguide-native/src/styles/themes.ts
- packages/styleguide-native/src/styles/typography.ts
- packages/styleguide/src/styles/expo-theme.css
- packages/styleguide/src/styles/themes.ts
- packages/styleguide/src/styles/typography.ts
As we update our docs design, I found that our current header sizes are too large for general-purpose UI. This PR adds "xl" versions of the headers (appropriate for marketing pages) alongside "default" headers (appropriate for prose, general-purpose UI).
Since this is a breaking change, also removed the `canvas` style, since it was deprecated.
> [styleguide] Adds xl/default headers

- packages/styleguide-native/src/styles/themes.ts
The `screen` background color for dark mode on native is the same as the `default` color, which made it impossible to differentiate the base layer and the UI on top of it.
I referenced the web color for `default` to correct this issue.
> [native] fix dark mode background.default color

- packages/styleguide-native/src/styles/themes.ts
- packages/styleguide/src/styles/expo-theme.css
- packages/styleguide/src/styles/themes.ts
While working on latest design updates in universe website and docs, I have spotted that Styleguide misses the "info" (blue) style while offering one for "error" (red), "warning" (yellow) and "success" (green). 
Those aliases are handy to use, and working with them is more pleasant than working with palette directly, so I have decided to add "info" to the exiting options.
This PR adds the "info" variable and aliases for both `styleguide` and `styleguide-native`. The values are based on the blue Home tile with small tweaks. I have tested them locally using palette values directly (separate for each theme).
Feel free to suggest any color alteration, I have no strong preferences on the selected shades.
> feat: add info styles for convenience

- packages/styleguide/src/index.ts
Currently the only way to use `IconProps` in other project is to directly import them from `dist` directory:
* https://github.com/expo/universe/pull/10111/files#diff-e933dd581115897d7c620afde3c2ef0cb037f05bc0b1c31cadc2caf5859e85d3R3
This small PR adds an export for the `IconProps` in the main package file.
> [styleguide] export `IconProps` in the main index file

- packages/styleguide-native/src/styles/themes.ts
- packages/styleguide/src/styles/expo-theme.css
- packages/styleguide/src/styles/themes.ts
Based on feedback from an initial website PR, this changes the button colors to have more contrast. Highlight in red are the colors I changed:
> Updates button colors

- packages/styleguide/src/components/BlockingSetInitialColorMode.tsx
- packages/styleguide/src/components/ThemeProvider.tsx
This small PR moves the `dark-mode` class from BODY to HTML element, which is required to fix the overscroll background color in Universe.
> [styleguide] move `dark-theme` class to HTML element

- packages/styleguide/src/styles/expo-theme.css
- packages/styleguide/src/styles/shadows.ts
Currently we lacking an ability to overwrite the box shadow using Tailwind classes, this is also a feature reduction comparing with default Tailwind theme shadow classes:
* https://tailwindcss.com/docs/box-shadow#removing-the-shadow
Add `shadows.none` theme value and required CSS variables which are set to `0 0 transparent` which is a reset value.
> add `none` shadow for overwrites and for cohesion with Tailwind

- packages/styleguide-base/rollup.config.mjs
- packages/styleguide-icons/rollup.config.mjs
- packages/styleguide-native/rollup.config.mjs
- packages/styleguide/package.json
- packages/styleguide/rollup.config.mjs
- yarn.lock
With the split of the packages and 8.0.0 alpha release we have set Rollup configs to output modules directly. 
Unfortunately, trying to update the package breaks both, ESM docs app and website app.
Set the Rollup target to be `cjs`, at least for now, so we can start the migration process.
> fix Rollup configuration for the packages

- packages/example-web/pages/icons.tsx
- packages/example-web/pages/ui.tsx
- packages/styleguide/package.json
- packages/styleguide/rollup.config.mjs
- packages/styleguide/src/components/Button/Button.tsx
- packages/styleguide/tailwind.js
- yarn.lock
There were some minor thing which slip through the cracks in the latest batch of PRs, let's address them.
The following changes have been made:
* remove QoL "smart" arrow appended to generic external button links
* remove `styleguide` dependency on the icons package (at least for now)
* add subtle interaction animation for non-disabled buttons
* fix `hocus` variant, which used the invalid focus pseudo class, leading to visual glitches
* update lock
> add subtle interaction animation, remove QoL arrow for external button links

- packages/example-web/pages/ui.tsx
- packages/styleguide/README.md
- packages/styleguide/src/components/Button/Button.tsx
At the beginning we decide to always apply capitalization for the buttons labels, but there are some cases when it would be useful to be able to skip the formatting.
This PR adds the `skipCapitalization` prop for the `Button` component which allows user to control when label formatting should apply.
> [styleguide] add Button prop to enable skipping capitalization

- packages/styleguide/src/components/Button/Button.tsx
- packages/styleguide/src/components/Button/ButtonBase.tsx
- packages/styleguide/src/components/Link/LinkBase.tsx
While switching to new Button in universe website, some tests starts to fail on `Button` interaction, when new `Button` has been placed in Radix popup/dialog.
The root cause for that is we don't fully pass `ref` down, this PR addresses this issue.
> [styleguide] forward ref for `Button`, add display names

- packages/example-web/components/headers.tsx
- packages/example-web/pages/index.tsx
- packages/example-web/pages/ui.tsx
- packages/styleguide/README.md
- packages/styleguide/package.json
- packages/styleguide/src/components/Button/Button.tsx
- packages/styleguide/tailwind.js
- yarn.lock
This PR performs the following chnages:
* [styleguide] add `@tailwind/typography` plugin with a stripped down default config to the theme
* [styleguide] improvements for the icon only Button
* [example-web] add `prose` usage example
* [example-web] add forced dark mode usage examples
> [styleguide] add typography plugin, icon Button tweaks, extend demos

- packages/example-web/pages/icons.tsx
- packages/styleguide-icons/figma.config.js
- packages/styleguide-icons/index.ts
We'd like to use the duotone icons from Figma in our website as we have them in our designs.
I also noticed that the `<PlanOnDemandIcon>` was not exported correctly and was missing the inner triangle in the icon, since there was a mask on the icon. I updated that icon and fixed it such that we don't need a mask.
1. In styleguide-icons, run `yarn build-icons`
2. In the parent directory of styleguide, run `yarn dev`
3. Then, open localhost:3000/icons
You should see duotone icons. Also, you should see the `<StoplightIcon>`.
> Adds duotone icons

- packages/example-web/pages/_app.tsx
- packages/example-web/pages/icons.tsx
While testing out the new Duotone icons variant addition, I have spotted that icons page in test app started to lag a bit.
This happens due to shear amount of DOM we output in there (3500+ SVG icons), so I decided to implement basic filters and search functionality.
Display only outline icons by default to aid page performance, add filters for icon variants, add very basic search implementation.
https://github.com/expo/styleguide/assets/719641/903542b2-5835-42ec-9579-d9cabe4ba457
> [example-web] add search and filters for icon list

- package.json
- packages/example-web/package.json
- packages/styleguide-base/package.json
- packages/styleguide-base/rollup.config.mjs
- packages/styleguide-icons/package.json
- packages/styleguide-icons/rollup.config.mjs
- packages/styleguide-native/package.json
- packages/styleguide-native/rollup.config.mjs
- packages/styleguide/package.json
- packages/styleguide/rollup.config.mjs
- yarn.lock
Currently, we ship our packages bundles as they are compiled. We can shave off a few kilobytes from the end bundle by applying a minification.
Add Terser to the Rollup pipeline, move common used dependencies to the workspace level, bump and align dependencies versions, fix few warnings and config mistakes.
Bundle sizes on disk in bytes before and after minifcation:
* `styleguide`: 92 813 -> 70 434
* `styleguide-base`: 23 291 -> 17 049
* `styleguide-native`: 41 469 -> 30 426
> [workspace] use Terser to minify bundles, cleanup dependencies

- packages/styleguide/tailwind.js
Why working on new Styleguide conversion in Expo dashboard and new Home page I have found that there are cases, where we were using background semantic colors for `stroke` SVG attribute.
It is possible to use the raw palette colors in there, but from time to time dark theme scope alterations are required.
This PR adds the semantic background colors to our TW theme `stroke` classes. I have to use `bg-` prefix, since semantic text colors are propagated by default to strokes.
After making changes to the theme I have build the package and tested the new classes using example-web (but I did not add any permanent test cases for that).
> [styleguide] allow using semantic background colors for `stroke`

- packages/example-web/package.json
- packages/example-web/pages/colors.tsx
- packages/styleguide-icons/package.json
- packages/styleguide/package.json
- packages/styleguide/tailwind.js
- yarn.lock
During the latest development towards TW adoption on the website we have introduced few more changes to our TW config. However, part of those can be moved in into our generic config, so other sites/products can also benefit from those additions, and this PR does exactly that.
Move in into base TW config the project icon background colors, icon classes safelist, theme settings, additional scale options and few other utility classes.
I have also added the project colors previe win the example app and bumped the `tailwind-merge` across the workspace.
> [styleguide] move in more general website config changes, bump merge helper

- packages/styleguide/rollup.config.mjs
Superseds #67
Fixes the incorrect initial theme setting when dark mode was set as default by preventing Terser from removing `*ColorMode` function during output `dist` optimization and compression.
The changes have been tested with included in repo `example-app`.
> fix initial theme apply by preventing color mode functions removal

- packages/example-web/pages/icons.tsx
- packages/styleguide/src/logos/OrbitLogo.tsx
- packages/styleguide/src/logos/index.tsx
We use custom SVG to represent Orbit in our services, so it's time to import the logo into styleguide.
Add orbit logo component to the `@expo/styleguide` package. Update example app list.
> [styleguide] add Orbit logo

- lerna.json
- package.json
- yarn.lock
Lerna v6 is not compatible with Prettier v3, from the related issues looks like updating Lerna to v7 fixes the issue.
> [workspace] update Lerna to latest version

- packages/search-ui/src/Items/ExpoDocsItem.tsx
- packages/search-ui/src/components/CommandMenuTrigger.tsx
- packages/search-ui/src/styles/expo-search-ui.css
There were small styling issues when testing integration in our docs, which are caused by loading order of styles.
This PR alters code a bit, so the problematic overwrites should not happen.
> [search-ui] tweaks for styling issues when used in docs

- packages/example-web/pages/ui.tsx
- packages/search-ui/src/components/CommandMenu.tsx
- packages/search-ui/src/components/CommandMenuTrigger.tsx
- packages/search-ui/src/styles/expo-search-ui.css
To do not overcomplicate layouts logic we need to make sure using multiple triggers and sharing dialog state via context is possible.
The example app has been updated to include multiple triggers to test the change.
> [search-ui] allow multiple triggers, style tweaks

- packages/example-web/components/search/QuickActionItem.tsx
- packages/example-web/package.json
- packages/search-ui/index.ts
- packages/search-ui/src/Items/ExpoDocsItem.tsx
- packages/search-ui/src/Items/RNDirectoryItem.tsx
- packages/search-ui/src/Items/RNDocsItem.tsx
- packages/search-ui/src/components/CommandItemBaseWithCopy.tsx
Re-export `Command.Item` from the `search-ui` package to prevent using `cmdk` exports directly for custom components.
Add `@expo/styleguide` packages entries to the example app dependencies to fix CI build errors.
> [search-ui] re-export CMDK `Item` component

- packages/example-web/pages/_document.tsx
- packages/styleguide/tailwind.js
- yarn.lock
While adding a library that modifies the HTML element class I have spotted that Tailwind `dark:` scope styles stops to apply, when there is an another class added.
Correct the Tailwind config dark mode matcher by loosening check.
> [styleguide] fix Tailwind config dark mode matcher

- packages/search-ui/src/components/CommandFooter.tsx
Because we like Algolia DocSearch. 🙂 
Add link to the Algolia logo in the footer of Search UI dialog.
> [search-ui] add link to Algolia logo in the footer

- package.json
- packages/example-web/package.json
- packages/example-web/pages/_app.tsx
- packages/example-web/pages/_document.tsx
- packages/search-ui/package.json
- packages/styleguide-icons/package.json
- packages/styleguide/package.json
- packages/styleguide/src/helpers/mergeClasses.ts
- yarn.lock
There was a new [Tailwind release](https://tailwindcss.com/blog/tailwindcss-v3-4), let's bump to it, and make sure `tw-merge` works as expected.
Update Tailwind, Tailwind Merge, Rollup setup and several other dependencies in workspace and packages.
Update the `tw-merge` config to match v2 changes, test out the updated packages in `example-web` tests project.
> bump Tailwind, tw-merge and other dependencies in the workspace

- packages/styleguide-icons/mergeClasses.ts
- packages/styleguide/src/components/Button/Button.tsx
- packages/styleguide/src/helpers/mergeClasses.ts
- packages/styleguide/tailwind.js
* [styleguide-icons] fix Tailwind merge config
* [styleguide] extend default Tailwind config
Looks like small regression slip through, when updating to new `tailwind-merge` version, which caused icon components issue, where the default size class ws not removed correctly, when use provide a custom one.
The Tailwind. config extension ports the custom classes uses in other projects, to make them generally available across all apps. I have also added a missing custom `size`, which custom variant we had for width and height already.
> minor tweak and fixes for packages

- packages/example-web/package.json
- packages/example-web/pages/ui/components.tsx
- packages/styleguide/src/components/Link/LinkBase.tsx
- yarn.lock
There are few, edge cases when it's unwanted to use Next Link component at all.
This PR adds a prop which allows Styleguide users to decide if they want to relay on raw HTML `a` tag instead.
Changes have been applied for `LinkBase` which is a building block of other intractable components. The dedicated tests have been added to web example app.
> [styleguide] add an ability to skip Next Link usage

- packages/example-web/package.json
- packages/styleguide-icons/figma.config.js
- yarn.lock
Refs https://github.com/expo/expo/issues/27047
Alter the embedded `id` in icon SVG DOM tree. Use the following pattern: `{iconName}-{variant}-icon` to avoid conflicts like mentioned in the referenced issue.
> [styleguide-icons] alter the embedded `id` in icon SVG DOM tree

- packages/example-web/components/headers.tsx
- packages/example-web/data/styleguideEntries.ts
- packages/example-web/package.json
- packages/example-web/pages/colors.tsx
- packages/search-ui/package.json
- packages/styleguide-icons/package.json
- packages/styleguide/package.json
- packages/styleguide/tailwind.js
- yarn.lock
The latest version of Tailwind and `tailwind-merge` includes fixes which we would like to have upstream.
* Update `taliwindcss` and `tailwind-merge` dependencies to the latest releases
* Add missing fill and gradient colors
* Align `@tailwindcss/typography` package version
* List semantic color on the Colors page of Styleguide example app
> [workspace] update Tailwind and merge helper, list semantic colors

- packages/example-web/pages/_app.tsx
- packages/example-web/pages/colors.tsx
- packages/styleguide/tailwind.js
Instead of extending, overwrite the `gradientColorStops` definitions in Tailwind theme, don't use `bg-` prefix for semantic colors.
The changes have been tested with locally updated package used inside `example-web` app.
> [styleguide] fix up the Tailwind theme gradient stops

- packages/example-web/components/Sidebar.tsx
- packages/example-web/merge-icon-imports.js
- packages/example-web/pages/icons.tsx
- packages/styleguide/tailwind.js
Move-in commonly used Tailwind theme extensions across our apps to avoid the definition repetition. The list includes asset shadows (very blurry, commonly used when presenting images or graphs) and base set of animations and their animations.
The Tailwind theme changes have been tested using the build-in example-web app, which now includes subtle load animation to make sure that theme definitions are working correctly.
I have also added a more gracefully way to fail when directories listed in `merge-icons-imports` script does not exist, and fixed the hardcoded path, since it was causing some issues when running on Windows.
https://github.com/user-attachments/assets/2de9bc72-9c20-41b0-83cb-240942dd7f4d
> [styleguide] move-in commonly used Tailwind theme extensions

- package.json
- packages/example-web/merge-icon-imports.js
- packages/example-web/package.json
- packages/example-web/pages/_app.tsx
- packages/example-web/pages/icons.tsx
- packages/search-ui/package.json
- packages/styleguide-icons/package.json
- packages/styleguide/package.json
- packages/styleguide/tailwind.js
- yarn.lock
We have noticed some mistakes and confusion due to abundance of screen width scopes. 
This chnageset alters the Tailwind theme configuration in a way which will reduce the scopes set to those which are more preferred to use. The updated theme has been tested in `example-web` app.
Additionally, I have bumped and aligned most of the package and workspace dependencies, and optimized the workspace lint, by ignoring most of the generated files.
> improve screen scopes, dependencies update/align, lint fixes

- packages/search-ui/package.json
- packages/search-ui/rollup.config.mjs
- packages/search-ui/src/Items/ExpoBlogItem.tsx
- packages/search-ui/src/components/CommandMenu.tsx
- packages/search-ui/src/types.ts
- packages/search-ui/src/utils.ts
- packages/search-ui/tsconfig.json
- yarn.lock
Refs https://linear.app/expo/issue/ENG-10901/[reader-facing]-v2-add-a-search-ui-that-searches-blog-content-and-docs
This PR adds the globally available Expo Blog posts section the the Search UI component. 
Since we are using the CDN those request should not have meaningful impact on our limits/plan.
> [search-ui] add Expo Blog posts section

- packages/example-web/components/ButtonsRow.tsx
- packages/example-web/pages/ui/components.tsx
- packages/search-ui/package.json
- packages/styleguide-icons/package.json
- packages/styleguide-icons/src/mergeClasses.ts
- packages/styleguide/package.json
- packages/styleguide/src/components/Button/Button.tsx
- packages/styleguide/src/helpers/mergeClasses.ts
- packages/styleguide/src/styles/expo-theme.css
- packages/styleguide/src/styles/themes.ts
- packages/styleguide/tailwind.js
- yarn.lock
Looks like the build-in destruction theme variants are in some cases "too bold".
Include new `tertiary-destructive` Button theme, which is based on already existing `tertiary` variant, but uses the red palette, as a base.
Additionally, I have added new `2xs` button size, since there were the cases forcing use to downsize the existing smaller Button, this also surfaced the issue with `icon-2xs` sizing, which was not present in `styleguide-icons` package class deduplicate mechanism, which caused that other icon class would overwrite that one.
Since we would need to release new packages anyway, I have also updated few of the shared dependencies.
The changes have been reviewed locally, by running `example-web` app.
> [styleguide] Button: add `tertiary-destructive` theme, add `2xs` size

- packages/example-web/pages/icons.tsx
- packages/styleguide-icons/svgr-icon-template.js
- packages/styleguide/tailwind.js
- yarn.lock
Stan reported to me that most of our  icons does not look great in Safari when using small sizes.
Force icons rendering on the GPU (via `translateZ(0)`), which also affects slightly icons rendering on other browsers - basically float point pixel values are calculated with greater precision, which affect slightly perceived stroke width of some icons.
In general, Safari SVG support seems a bit off in comparison to Chrome and FF. Hopefully we would be able to remove this workaround at some point in time:
* https://wpt.fyi/results/svg?label=stable&product=safari&product=chrome&product=firefox
https://github.com/user-attachments/assets/3e16142e-9765-40fc-8f63-92fc35ce51ce
> [styleguide-icons] improve small icons render on Safari

- packages/styleguide-icons/figma.config.js
We lost easy testing ability with latest optimization efforts (since we cannot longer identify if correct icon has been rendered):
* #96
Remove `cleanupIDs` optimization, `id`s might be be used directly in the code, but we relaying on them for testing purposes.
Made sure locally, that after removing the optimization, icon names are present.
> [styleguide-icons] do not cleanup IDs, they are used for testing

- packages/styleguide/src/styles/expo-theme.css
Will fix https://github.com/expo/expo/issues/33560 after package upgrade in our apps.
Force set `color-scheme: dark` in dark mode to inform browser that dark themed native components should be used, if available. Some of our apps use fully custom scrollbars, but there are cases where prefer staying with native presentation.
> [styleguide] force "dark" color scheme in dark theme

- packages/styleguide/src/helpers/mergeClasses.ts
We have a custom `heading-*` classes declared, but they are not deduplicated correctly.
* https://github.com/expo/styleguide/blob/main/packages/styleguide/tailwind.js#L304
Add the `heading` classes definition to the `mergeClasses` utils config, so issues in manually written code are spotted on the fly, and for concatenated class strings the lower priority classes are stripped.
> [styleguide] support custom `heading-*` classes in merger

- .github/workflows/deploy-preview.yml
- packages/example-web/next.config.js
- packages/search-ui/src/Items/RNDirectoryItem.tsx
Spotted that due to npm API falkiness we miss download data for several pages, which caused NaNs when attempting to reformat a number.
Hande download count correctly as optional, add small icons to match the metadata visualization on the React Native directory side.
Additionally, I have updated the GHA workflow to allow fetching correct evn data, when deploying to the PROD deployment, see:
* https://github.com/expo/styleguide/actions/runs/14016971214/job/39243832065
> [search-ui] improve RND item description, fix NaNs

- packages/example-web/components/search/SearchMenu.tsx
- packages/search-ui/src/components/CommandItemBaseWithCopy.tsx
Spotted that after upgrading `search-ui` package in docs does not allow all entries to be open via meta click properly.
If meta click is detect, treat all links as external ones.
I have added a stub URL transform to the `search-ui` instance used in `example-web`, to cover more use-cases.
> [search-ui] fix meta click feature with transformed URLs

- package.json
- packages/example-native/package.json
Spotted that ESLint still attempts to lint generated file in `example-native` app.
Correct the ESLint ignores.
> [example-native] prevent linting generated file

- packages/styleguide-icons/svgr-icon-template.js
- packages/styleguide/tailwind.js
[styleguide] height based media breakpoint
[styleguide-icons] apply icons shrink prevention by default
Add height based media breakpoint required for navigation optimization in docs.
Add `shrink-0` class to icons by default, add it to the safelist to prevent unwanted behaviour by default.
The changes have been reviewed locally by building all packages, and then running example web
> [styleguide] height based media breakpoint

- package.json
- packages/example-web/components/ButtonsRow.tsx
- packages/example-web/components/DemoTile.tsx
- packages/example-web/components/Sidebar.tsx
- packages/example-web/components/SidebarLink.tsx
- packages/example-web/components/headers.tsx
- packages/example-web/components/search/QuickActionItem.tsx
- packages/example-web/components/search/StyleguideItem.tsx
- packages/example-web/package.json
- packages/example-web/pages/_app.tsx
- packages/example-web/pages/_document.tsx
- packages/example-web/pages/colors.tsx
- packages/example-web/pages/icons.tsx
- packages/example-web/pages/index.tsx
- packages/example-web/pages/layouts.tsx
- packages/example-web/pages/typography.tsx
- packages/example-web/pages/ui/components.tsx
- packages/styleguide/tailwind.js
- yarn.lock
Using custom object-like (`raw`) breakpoints breaks autogeneration of some properties:
Drop custom screen from the preset (it can be defined manually in app which need it, which should help us avoid unwanted side-effects related to auto generated by tailwind screen classes. I have also removed legacy custom `screen-xs` with definition.
Additionally, the `example-web` app includes now Layouts page explaining available screens and fully-fledged lint setup, including Tailwind part, which mimic the general config we use in apps utilizing styleguide.
> fix styleguide screens, improve example-app setup

- packages/example-web/components/Sidebar.tsx
- packages/example-web/components/SidebarLink.tsx
- packages/example-web/components/headers.tsx
- packages/example-web/pages/_app.tsx
- packages/example-web/pages/layouts.tsx
- packages/example-web/pages/typography.tsx
- packages/styleguide/tailwind.js
Use plugins API to define required height-based media query.
Add test case for the new breakpoint on the example app logo, additionally, I have ugraded and make more informative the Layout page.
> compat height variant, example app improvements

- packages/example-web/common/icon-imports.ts
Add LogRocket and Sentry icons, refetch set to verify icons are present, regenerate website imports file.
> add LogRocket and Sentry icons

- packages/search-ui/src/components/AIPromptResult.tsx
- packages/search-ui/src/components/BarLoader.tsx
- packages/search-ui/src/components/CommandMenuContent.tsx
- packages/search-ui/src/styles/expo-search-ui.css
We want to emphasize a bit more the experimental nature of Expo AI assistant feature in Search UI.
Add sub-line to the trigger option, add note in prompt result footer denoting the experimental nature of Expo AI assistant feature.
Update styles based on spotted issue in docs app, tweak prompt result layout in mobile view.
> [search-ui] experimental notes, style tweaks and fixes

- packages/styleguide/src/components/Theme/ThemeProvider.tsx
Adds a helper to know what theme is actually applied at a given time; if `auto`, then returns what the user's browser preferences are. 
Having trouble getting the styleguide running locally, so haven't been able to test yet.
> [styleguide] Export `activeTheme` from `ThemeProvider`

- packages/example-web/components/ColorTile.tsx
- packages/example-web/components/Sidebar.tsx
- packages/example-web/next.config.js
- packages/example-web/pages/colors.tsx
- packages/example-web/pages/layouts.tsx
- packages/example-web/pages/typography.tsx
- packages/example-web/pages/ui/components.tsx
- packages/styleguide/src/components/Button/Button.tsx
- packages/styleguide/src/components/Theme/BlockingSetInitialColorMode.tsx
- packages/styleguide/src/styles/expo-theme.css
- packages/styleguide/tailwind.js
Summary of changes:
* add `"preview"` semantic color, for new type of `InlineHelp`/`Callout` components
* fix element validation in`Button` helper
* increase the roundness of the largest `Button` variant
* make `BlockingSetInitialColorMode` injection minification proof
* add few common extensions to the Tailwind theme config
* update Example Web app content and theme toggler
> [styleguide] add "preview" semantic color, small tweaks

- packages/search-ui/src/components/AIPromptResult.tsx
Fix ENG-16978 ENG-16979
- Run example-web, open search UI > AI, ask a question.
- Update "Source" references so that sentencs end with a period and references/links are marked with "Source: " prefix.
> [search-ui] Fix line spacing in AI search for header and update "Sources" reference
